steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build Next.js
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 3: Package into a container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/health-consultation', '.'
    ]

  # Step 4: Push to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/health-consultation'
    ]

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'health-consultation',
      '--image', 'gcr.io/$PROJECT_ID/health-consultation',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/health-consultation'
